version: "3.8"
# Has to be in quotes otherwise it'll be interpreted as an integer
volumes:

  mariadb_data:
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/kbrice/data/mariadb_data"
  wordpress_data:
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/kbrice/data/wordpress_data"

networks:
  docker-network:
    name: docker-network

services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
      # Volumes are used to store and share data between containers.
      # The data stored in /var/lib/mysql  will remain even if the container
      # is removed or recreated. So the database data will survive restarts
      # and upgrades.
    networks:
      - docker-network
    expose:
      - "3306"
    restart: always
    env_file:
      - .env

  ngnix:
    container_name: ngnix
    build: ./requirements/nginx
    ports:
      - 443:443
      # port of the host : port of the container running this image
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - docker-network

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    # Checks whether mariadb is running first before wordpress starts
    build: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - docker-network
    expose:
      - "9000"

